Update c_to_mem to link the file before dumping

diff --git a/tools/c_to_mem b/tools/c_to_mem
--- a/tools/c_to_mem
+++ b/tools/c_to_mem
@@ -5,35 +5,20 @@ FAIL() {
     exit 1
 }
 
-CC_CANDIDATES=(
-    riscv64-unknown-linux-gnu-gcc
-    /pkgs/riscv-gnu-toolchain/riscv-gnu-toolchain/bin/riscv64-unknown-linux-gnu-gcc
-)
-for i in "${CC_CANDIDATES[@]}" ; do
-    [ -n "$CC" ] && break
-    if which "$i" > /dev/null 2>/dev/null ; then
-        CC="$i"
-    fi
-done
-CC=${CC:-"riscv64-unknown-linux-gnu-gcc"}
-
-OBJDUMP_CANDIDATES=(
-    riscv64-unknown-linux-gnu-objdump
-    /pkgs/riscv-gnu-toolchain/riscv-gnu-toolchain/bin/riscv64-unknown-linux-gnu-objdump
-)
-for i in "${OBJDUMP_CANDIDATES[@]}" ; do
-    [ -n "$OBJDUMP" ] && break
-    if which "$i" > /dev/null 2>/dev/null ; then
-        OBJDUMP="$i"
-    fi
-done
+TOOLCHAIN=riscv32-unknown-elf
+CC="${TOOLCHAIN}-gcc"
+LD="${TOOLCHAIN}-ld"
+OBJDUMP="${TOOLCHAIN}-objdump"
 
 # Check for dependencies
-if [ -z "$CC" ] ; then
+if ! which "$CC" >/dev/null 2>/dev/null ; then
     FAIL "Could not find a compiler"
 fi
-if [ -z "$OBJDUMP" ] ; then
-    FAIL "Could not find llvm-objdump"
+if ! which "$LD" >/dev/null 2>/dev/null ; then
+    FAIL "Could not find a linker"
+fi
+if ! which "$OBJDUMP" >/dev/null 2>/dev/null ; then
+    FAIL "Could not find objdump"
 fi
 
 # Check usage args
@@ -52,6 +37,10 @@ fi
 set -e
 
 "$CC" -march=rv32i -mabi=ilp32 -fpic -ggdb -O0 -c "$TARGET" -o "$BASEFILENAME.o"
-"$OBJDUMP" -d "$BASEFILENAME.o" \
+"$LD" "$BASEFILENAME.o" -o "$BASEFILENAME"
+"$OBJDUMP" -d "$BASEFILENAME" \
     | sed 's/^ *//;/^[a-f0-9]*:/!d;s/  .*//;s/ //g' \
     > "$BASEFILENAME.mem"
+"$OBJDUMP" -d "$BASEFILENAME" \
+    | sed '/<_start>/!d;s/ .*//;s/^/PC: /' \
+    >> "$BASEFILENAME.mem"
